language: cpp

dist: bionic

jobs:
  include:
    - name: "Linux (Clang compiler)"
      os: linux
      compiler: "clang-10"
      env: OS=linux COMPILER=clang CLANG_VERSION=10
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - llvm-10
            - llvm-10-runtime
            - llvm-10-tools
            - llvm-10-dev
            - cmake
            - libgtest-dev
            - build-essential
          update: true

branches:
  only:
    - master
    - dev

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  - export CC="clang-10" CXX="clang++-10"
# Build scripts
script: 
  - llvm-config --version
  - mkdir -p build
  - cd build
  - cmake .. 
  - make test

notifications:
  email:
    on_success: never
