language: cpp
compiler: clang
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq clang
  # cppcheck
  - sudo apt-get install -qq cppcheck

script: 
  # Build and run this project
  mkdir build
  cd build
  cmake ..  
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
