# Programming language definition
language: cpp

# OS environment
dist: bionic

# Build matrix (OS, compiler)
jobs:
  include:
    - name: "Linux (Clang compiler)"
      os: linux
      compiler: clang
      env: OS=linux COMPILER=clang CLANG_VERSION=9
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - llvm-9
            - llvm-9-tools
            - llvm-9-dev
            - cmake
            - libgtest-dev
          update: true
    - name: "MacOS"
      os: osx
      compiler: clang
      env: OS=osx COMPILER=clang
      osx_image: xcode11.3

# Branches to build
branches:
  only:
    - master

# Scripts that run before install
before_install:
  # clang, libc++, libc++abi
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}" LLVM_DIR="/usr/include/llvm-9/lib/cmake" ; fi
  - if [ "$OS" == "osx" ]; then brew update; fi
  - if [ "$OS" == "osx" ]; then brew install llvm; fi
  - if [ "$OS" == "osx" ]; then export LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include"; fi
  - if [ "$OS" == "osx" ]; then git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake .. && make && make install ; fi
# cmake
  - cmake --version
  # git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  # llvm
  - git clone https://github.com/llvm/llvm-project.git
cache:
 directories:
  - llvm
# Build scripts
script: 
  - mkdir gtest-bin && cd gtest-bin && cmake /usr/src/gtest && make && cd ..
  - echo "LLVM config" 
  - llvm-config --prefix
  - llvm-config --src-root
  - llvm-config --obj-root
  - llvm-config --includedir
  - llvm-config --bindir
  - llvm-config --libdir
  - llvm-config --cxxflags
  - llvm-config --ldflags
  - rm -r llvm
  - cd llvm-project
  - mv llvm .. 
  - cd .. 
  - cd llvm && ls
  - cd ..
  - mkdir -p build
  - cd build
  - cmake .. 
  - make

# Don't send notifications on success
notifications:
  email:
    on_success: never
